---
name: 'release'

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  buildWin:
    runs-on: 'windows-latest'

    steps:
      - name: '🔧 setup node'
        uses: docker://node:20
        with:
          cache: 'yarn'
          node-version: 16
          cache-dependency-path: 'yarn.lock'

      - run: 'npm install'
      - run: 'npm run build'

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'
          files: |
            release/0.0.0.0
        id: 'automatic_releases'
